version: 2

jobs:
  build:
    macos:
      xcode: "9.0"

    steps:
      - checkout

      - run:
          name: Generate Xcode project file
          command: swift package generate-xcodeproj

      - run:
          name: Run iOS tests
          command: xcodebuild test -scheme SnapshotTesting-Package -destination platform="iOS Simulator,name=iPhone 8,OS=11.0"
          environment:
            SNAPSHOT_ARTIFACTS: $CIRCLE_ARTIFACTS

      # - run:
      #     name: Run macOS tests
      #     command: xcodebuild test -scheme SnapshotTesting-Package -destination platform="macOS"
      #     environment:
      #       SNAPSHOT_ARTIFACTS: $CIRCLE_ARTIFACTS
