version: 2

jobs:
  build:
    linux:

    steps:
      - checkout

      - run:
          name: Generate Xcode project file
          command: swift package generate-xcodeproj

      - run:
          name: Run iOS tests
          command: swift test
          environment:
            SNAPSHOT_ARTIFACTS: $CIRCLE_ARTIFACTS
