version: 2

jobs:
  build:
    macos:
      xcode: "10.0.0"

    steps:
      - checkout

      - run:
          name: Mac info
          command: system_profiler SPSoftwareDataType

      - run:
          name: Generate Xcode project file
          command: swift package generate-xcodeproj

      - run:
          name: Run iOS tests
          command: make test-ios

      - run:
          name: Run macOS tests
          command: make test-macos

      - run:
          name: Run Swift tests
          command: make test-swift

      - store_artifacts:
          path: /tmp
